name: push docker image

on: 
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-16.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: login
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: build
        run: docker build . -t planetariumhq/nine-chronicles-http-gateway:git-${{ github.sha }}
      - name: push (publish)
        run: docker push planetariumhq/nine-chronicles-http-gateway:git-${{ github.sha }}
